# Copy with specific changes for cortex-a72 (chipset RPI 4) from [openembedded-core/meta/conf/machine/qemuarm64.conf @cc4695f65beb]
# Changes for cortex-a72 are required to ensure that the same packages and sstate are used for both raspberrypi4-64 and qemu-rpi4-64 machines. 
# This is important for development and testing purposes, as it allows for consistent builds across different machine configurations.
#@TYPE: Machine
#@NAME: QEMU arm64 with the Raspberry Pi 4 CPU
#@DESCRIPTION: qemuarm64 tuned for the Cortex-A72 of the Raspberry Pi 4, so both
#@DESCRIPTION: machines share their packages and sstate. Development and testing only.

require conf/machine/include/arm/armv8a/tune-cortexa72.inc
require conf/machine/include/qemu.inc

DEFAULTTUNE = "cortexa72-nocrypto"
MACHINEOVERRIDES =. "qemuarm64:"
KMACHINE:qemu-rpi4-64 = "qemuarm64"

KERNEL_IMAGETYPE = "Image"

PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot"
UBOOT_MACHINE ?= "qemu_arm64_defconfig"

SERIAL_CONSOLES ?= "115200;ttyAMA0 115200;hvc0"

# For runqemu
QB_SYSTEM_NAME = "qemu-system-aarch64"
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu cortex-a72"
QB_SMP ?= "-smp 4"
QB_CPU_KVM = "-cpu host -machine gic-version=3"
# For graphics to work we need to define the VGA device as well as the necessary USB devices
QB_GRAPHICS = "-device virtio-gpu-pci"
QB_OPT_APPEND = "-device qemu-xhci -device usb-tablet -device usb-kbd"
# Virtio Networking support
QB_TAP_OPT = "-netdev tap,id=net0,ifname=@TAP@,script=no,downscript=no"
QB_NETWORK_DEVICE = "-device virtio-net-pci,netdev=net0,mac=@MAC@"
# Virtio block device
QB_ROOTFS_OPT = "-drive id=disk0,file=@ROOTFS@,if=none,format=raw -device virtio-blk-pci,drive=disk0"
# Virtio serial console
QB_SERIAL_OPT = "-device virtio-serial-pci -chardev null,id=virtcon -device virtconsole,chardev=virtcon"
QB_TCPSERIAL_OPT = "-device virtio-serial-pci -chardev socket,id=virtcon,port=@PORT@,host=127.0.0.1,nodelay=on -device virtconsole,chardev=virtcon"
