# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-smart-column"
BBFILE_PATTERN_meta-smart-column = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-smart-column = "6"

LAYERDEPENDS_meta-smart-column = "core"
LAYERSERIES_COMPAT_meta-smart-column = "wrynose"
